# Generated by Django 3.0.2 on 2020-01-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hi',
        ),
    ]
